info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
  build:
    artifact: '@project.artifactId@'
    group: '@project.groupId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servidores_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

